
import React from 'react';
import AnimatedBackground from './AnimatedBackground';
import { ArrowRight, Sparkles } from 'lucide-react';
import { motion } from 'framer-motion';

const Hero = () => {
  // Animation variants
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.15,
        delayChildren: 0.3
      }
    }
  };

  const itemVariants = {
    hidden: { y: 40, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
      transition: { duration: 0.7, ease: [0.22, 1, 0.36, 1] }
    }
  };

  return (
    <section className="relative min-h-screen pt-20 pb-32 overflow-hidden bg-gradient-to-br from-gray-900 via-gray-800 to-black">
      <AnimatedBackground />
      
      {/* Decorative elements */}
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-yellow-500/20 rounded-full blur-3xl"></div>
        <div className="absolute top-1/2 -left-40 w-80 h-80 bg-yellow-600/20 rounded-full blur-3xl"></div>
        <div className="absolute bottom-40 right-1/3 w-60 h-60 bg-yellow-400/10 rounded-full blur-3xl"></div>
      </div>
      
      <div className="container-section relative z-10">
        <motion.div
          initial="hidden"
          animate="visible"
          variants={containerVariants}
          className="max-w-5xl mx-auto text-center"
        >
          <motion.div 
            variants={itemVariants}
            className="inline-flex items-center px-4 py-2 rounded-full bg-yellow-500/20 text-yellow-300 mb-6 backdrop-blur-sm border border-yellow-500/30"
          >
            <Sparkles className="w-4 h-4 mr-2" />
            <span className="text-sm font-medium font-inter tracking-wide">Turn Data Into Stories</span>
          </motion.div>
          
          <motion.h1 
            variants={itemVariants}
            className="font-inter font-bold text-4xl md:text-6xl lg:text-8xl tracking-tight max-w-4xl mx-auto mb-6 leading-[1.1]"
          >
            <span className="text-black">Your Work</span>, <span className="text-transparent bg-clip-text bg-gradient-to-r from-yellow-400 via-yellow-500 to-yellow-600 font-extrabold">Wrapped</span> ✨
          </motion.h1>
          
          <motion.p 
            variants={itemVariants}
            className="font-inter text-xl md:text-2xl text-gray-300 max-w-3xl mx-auto mb-8 leading-relaxed"
          >
            Turn spreadsheets into delightful AI-generated highlight reels for your team or audience.
          </motion.p>
          
          <motion.div 
            variants={itemVariants}
            className="flex flex-col sm:flex-row justify-center items-center gap-4 mb-16"
          >
            <a href="#auth" className="bg-gradient-to-r from-yellow-500 to-yellow-600 hover:from-yellow-600 hover:to-yellow-700 text-black font-semibold py-4 px-8 rounded-xl transition-all hover:shadow-xl hover:shadow-yellow-500/25 hover:scale-[1.02] active:scale-[0.98] flex items-center group font-inter text-lg">
              Try Me
              <ArrowRight className="ml-2 w-5 h-5 transition-transform group-hover:translate-x-1" />
            </a>
            <a href="#how-it-works" className="border border-gray-600 bg-gray-800/50 backdrop-blur-sm text-white font-medium py-4 px-8 rounded-xl transition-all hover:bg-gray-700/50 hover:scale-[1.02] active:scale-[0.98] font-inter text-lg">
              See How It Works
            </a>
          </motion.div>
          
          {/* Hero Visual - Mock Wrapped Card */}
          <motion.div 
            variants={itemVariants}
            className="max-w-md mx-auto"
          >
            <div className="relative bg-gradient-to-br from-yellow-500 to-yellow-600 rounded-2xl p-8 shadow-2xl border border-yellow-400/20 backdrop-blur-sm">
              <div className="absolute top-4 right-4 text-xs bg-black/20 px-2 py-1 rounded-md text-white/80">
                Generated by AI
              </div>
              <div className="text-center">
                <div className="text-6xl mb-4">📊</div>
                <h3 className="text-black text-xl font-bold mb-2">Your Q4 Highlights</h3>
                <p className="text-black/80 text-sm mb-4">
                  You crushed 847 tasks this quarter! 🚀
                </p>
                <div className="bg-black/10 rounded-lg p-3">
                  <p className="text-black/90 text-xs">
                    Most productive day: Tuesday 💪
                  </p>
                </div>
              </div>
            </div>
          </motion.div>
        </motion.div>
      </div>
    </section>
  );
};

export default Hero;
