
import React from 'react';
import { motion } from 'framer-motion';
import { ChevronLeft, ChevronRight } from 'lucide-react';

const RealExamples = () => {
  const examples = [
    {
      emoji: "🤖",
      caption: "You spent 124 hours using AI this quarter",
      subtitle: "That's 3x more than last quarter!",
      gradient: "from-blue-500 to-purple-500"
    },
    {
      emoji: "🍿",
      caption: "Your top distraction? YouTube",
      subtitle: "47 hours of 'research videos' 😅",
      gradient: "from-red-500 to-pink-500"
    },
    {
      emoji: "📘",
      caption: "90% of your team adopted Notion",
      subtitle: "Organization level: Expert!",
      gradient: "from-indigo-500 to-blue-500"
    },
    {
      emoji: "☕",
      caption: "Coffee consumption: 247 cups",
      subtitle: "Productivity fuel achieved ✨",
      gradient: "from-amber-500 to-orange-500"
    },
    {
      emoji: "🎯",
      caption: "Goals completed: 156 out of 160",
      subtitle: "97.5% success rate - incredible!",
      gradient: "from-green-500 to-emerald-500"
    },
    {
      emoji: "📈",
      caption: "Revenue grew 34% this quarter",
      subtitle: "Best performance in company history",
      gradient: "from-purple-500 to-pink-500"
    }
  ];

  return (
    <section className="py-20 bg-gray-900" id="examples">
      <div className="container mx-auto px-6">
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, ease: [0.22, 1, 0.36, 1] }}
          viewport={{ once: true }}
          className="max-w-6xl mx-auto"
        >
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
              Real Examples
            </h2>
            <p className="text-xl text-gray-300 max-w-3xl mx-auto">
              See how AI transforms your boring spreadsheet data into engaging, shareable content
            </p>
          </div>

          {/* Mobile-style slides grid */}
          <div className="grid md:grid-cols-3 gap-6 mb-12">
            {examples.map((example, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                viewport={{ once: true }}
                className="relative"
              >
                {/* Mobile frame */}
                <div className="bg-gray-800 p-2 rounded-2xl shadow-2xl">
                  <div className={`bg-gradient-to-br ${example.gradient} rounded-xl p-6 text-white text-center relative overflow-hidden`}>
                    {/* AI Generated tag */}
                    <div className="absolute top-3 right-3 bg-black/30 px-2 py-1 rounded-md text-xs font-medium">
                      Generated by AI
                    </div>
                    
                    {/* Content */}
                    <div className="text-5xl mb-4">{example.emoji}</div>
                    <h3 className="text-lg font-bold mb-2 leading-tight">
                      {example.caption}
                    </h3>
                    <p className="text-sm opacity-90">
                      {example.subtitle}
                    </p>
                    
                    {/* Decorative pattern */}
                    <div className="absolute -bottom-4 -right-4 w-20 h-20 bg-white/10 rounded-full"></div>
                    <div className="absolute -top-4 -left-4 w-16 h-16 bg-white/10 rounded-full"></div>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>

          {/* Carousel navigation hint */}
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            transition={{ duration: 0.6, delay: 0.8 }}
            viewport={{ once: true }}
            className="flex justify-center items-center space-x-4 text-gray-400"
          >
            <ChevronLeft className="w-6 h-6" />
            <span className="text-sm">Swipe to see more examples</span>
            <ChevronRight className="w-6 h-6" />
          </motion.div>

          {/* CTA */}
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 1 }}
            viewport={{ once: true }}
            className="text-center mt-12"
          >
            <a 
              href="#auth" 
              className="bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-700 hover:to-indigo-700 text-white font-semibold py-4 px-8 rounded-xl transition-all hover:shadow-xl hover:shadow-purple-500/25 hover:scale-[1.02] active:scale-[0.98]"
            >
              Create Your Own Wrapped
            </a>
          </motion.div>
        </motion.div>
      </div>
    </section>
  );
};

export default RealExamples;
