// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtpfchphgatlbkigmvcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0cGZjaHBoZ2F0bGJraWdtdmNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTgyNjMsImV4cCI6MjA2NTQ5NDI2M30.2fK3iiAh6UvR-Xto_SI8CVvj6gNMPs1tAlyOn3x558Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);